#!/bin/bash

voicers=$1
english_text=$2

while read -r line || [[ -n "$line" ]]; do
    echo "$line"
    while IFS='' read -r voicer; do
        echo "    -> $voicer"
        say -v "$voicer"  $line
    done < $voicers
done < $english_text
