#!/bin/bash

voicers=$1
english_sentences_txt=$2

while read -r sentence || [[ -n "$sentence" ]]; do
    echo "$sentence"
    while IFS='' read -r voicer; do
        echo "    -> $voicer"
        say -v "$voicer"  $sentence
    done < $voicers
done < $english_sentences_txt
